name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for broken links
        run: |
          output=$(npx mintlify broken-links)
          echo "$output"
          if echo "$output" | grep -qi "found.*broken links in"; then
            echo "❌ Broken links detected!"
            exit 1
          else
            echo "✅ No broken links found"
          fi
